version: '3.1'


services:

 
  mysql:

      image: 'mysql:5.6'

      command: --default-authentication-plugin=mysql_native_password

      restart: always

      ports:

        - 3308:3306

      environment:

        MYSQL_ROOT_PASSWORD: work_distribution_pass

      volumes:

        - ./data/mysql:/var/lib/mysql

  node:
      build: .
      environment:
        - PORT=3010
      ports: 
        - 3010:3010
      command: npm start
