version: '3.1'


services:

 
  mysql:

      image: 'mysql:5.6'
      command: --default-authentication-plugin=mysql_native_password 
      ports:
        
        - 33015:3306
      environment:
        MYSQL_ROOT_PASSWORD: work_distribution_pass
  node:
      image: 'node'
      environment:
        - PORT=3010
      stdin_open: true
      tty: true
      restart: always
      depends_on:
        - mysql
      ports: 
        - 3010:3010
      command: ./initserver.sh
       